# Generated by Django 4.1.3 on 2022-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
