# Generated by Django 4.1.3 on 2022-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapp', '0002_exercises_is_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='exercises_users_answers',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
