# Generated by Django 4.1.3 on 2022-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnExerciesesOfUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('result', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Not Set', 'Not Set')], max_length=50)),
                ('code_for_example', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnQuizzesOfUsersPython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_quiz', models.TextField()),
                ('result', models.CharField(max_length=255)),
                ('hint', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Not Set', 'Not Set')], max_length=50)),
            ],
        ),
    ]
