# Generated by Django 4.1.3 on 2022-11-08 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzesPython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('admin_correct_answer', models.CharField(max_length=50)),
                ('section', models.CharField(choices=[('List', (('List Easy', 'List Easy🟡⚪️⚪️'), ('List Medium', 'List Medium🟡🟡⚪️'), ('List Difficult', 'List Difficult🟡🟡🟡'))), ('Tuple', (('Tuple Easy', 'Tuple Easy🟡⚪️⚪️'), ('Tuple Medium', 'Tuple Medium🟡🟡⚪️'), ('Tuple Difficult', 'Tuple Difficult🟡🟡🟡'))), ('Set', (('Set Easy', 'Set Easy🟡⚪️⚪️'), ('Set Medium', 'Set Medium🟡🟡⚪️'), ('Set Difficult', 'Set Difficult🟡🟡🟡'))), ('String', (('String Easy', 'String Easy🟡⚪️⚪️'), ('String Medium', 'String Medium🟡🟡⚪️'), ('String Difficult', 'String Difficult🟡🟡🟡'))), ('Dictionary', (('Dict Easy', 'Dict Easy🟡⚪️⚪️'), ('Dict Medium', 'Dict Medium🟡🟡⚪️'), ('Dict Difficult', 'Dict Difficult🟡🟡🟡'))), ('OOP', (('OOP Easy', 'OOP Easy🟡⚪️⚪️'), ('OOP Medium', 'OOP Medium🟡🟡⚪️'), ('OOP Difficult', 'OOP Difficult🟡🟡🟡'))), ('Any Else Thing', (('Any Easy', 'Any Easy🟡⚪️⚪️'), ('Any Medium', 'Any Medium🟡🟡⚪️'), ('Any Difficult', 'Any Difficult🟡🟡🟡')))], max_length=50)),
                ('code_image', models.ImageField(default='default.jpg', upload_to='code_photo')),
                ('solution', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes_Users_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, null=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzesapp.quizzespython')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
