# Generated by Django 4.1.3 on 2022-12-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzesapp', '0002_quizzespython_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzespython',
            name='code_test',
            field=models.TextField(blank=True),
        ),
    ]
