# Generated by Django 4.1.3 on 2022-12-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzesapp', '0003_quizzespython_code_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzespython',
            name='code_image',
        ),
        migrations.RemoveField(
            model_name='quizzespython',
            name='code_test',
        ),
        migrations.AddField(
            model_name='quizzespython',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
