# Generated by Django 4.1.3 on 2022-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzesapp', '0004_remove_quizzespython_code_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzespython',
            name='section',
            field=models.CharField(choices=[('List', (('Difficulty: Easy', 'List Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'List Medium🟡🟡⚪️'), ('Difficulty: Hard', 'List Difficult🟡🟡🟡'))), ('Tuple', (('Difficulty: Easy', 'Tuple Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'Tuple Medium🟡🟡⚪️'), ('Difficulty: Hard', 'Tuple Difficult🟡🟡🟡'))), ('Set', (('Difficulty: Easy', 'Set Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'Set Medium🟡🟡⚪️'), ('Difficulty: Hard', 'Set Difficult🟡🟡🟡'))), ('String', (('Difficulty: Easy', 'String Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'String Medium🟡🟡⚪️'), ('Difficulty: Hard', 'String Difficult🟡🟡🟡'))), ('Dictionary', (('Difficulty: Easy', 'Dict Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'Dict Medium🟡🟡⚪️'), ('Difficulty: Hard', 'Dict Difficult🟡🟡🟡'))), ('OOP', (('Difficulty: Easy', 'OOP Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'OOP Medium🟡🟡⚪️'), ('Difficulty: Hard', 'OOP Difficult🟡🟡🟡'))), ('Any Else Thing', (('Difficulty: Easy', 'Any Easy🟡⚪️⚪️'), ('Difficulty: Medium', 'Any Medium🟡🟡⚪️'), ('Difficulty: Hard', 'Any Difficult🟡🟡🟡')))], max_length=50),
        ),
    ]
