# Generated by Django 4.1.3 on 2022-12-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('decription', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('download', models.FileField(blank=True, null=True, upload_to='books')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.bookcategory')),
            ],
            options={
                'ordering': ('publish',),
            },
        ),
    ]
