# Generated by Django 4.1.3 on 2022-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='books/books_img/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
